apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: abtq3d2ks-go
  janus-idp.io/tekton: abtq3d2ks-go
  backstage.io/kubernetes-id: abtq3d2ks-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: abtq3d2ks-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
