apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: abtq3d2ks-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: abtq3d2ks-go 
  name: abtq3d2ks-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: abtq3d2ks-go 
